baseURL: https://wajidkhan.info
#baseURL: https://localhost:1313
languageCode: en-us
defaultContentLanguage: en
title: 
theme: academic
#googleAnalytics: UA-123456789-1
disqusShortname: Dr Khan
enableGitInfo: false

#taxonomies:
  #tag: tags
permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: Dr. Wajid Khan, PhD, <i>Policy, Strategy, Data, AI, Coder, Educator, Tech Consultant.</i> <br><br> <b>Engineering the Future!</b> 
  homeMetaContent: Dr. Wajid Khan Mastering the Art of AI and Data Science. Engineering the Future. Your Vision, My Code, Our Reality.
  footer: Dr  [Wajid Khan](https://wajidkhan.info/) 2007 -2024. 
  dateFormat: Jan 24, 2024
  codePenUser: DrKhan
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: true
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: Dr Wajid Khan
  # customCss:
  #   - css/custom_01.css
  #   - css/custom_02.css
  # customJs:
  #   - js/custom_01.js
  #   - js/custom_02.js
  # utterances:
  #   repo: username/username.github.io
  #   issueTerm: title
  #   theme: github-light

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Startup Tech Evaluation 
      url: /startup-tech-evaluation/
      weight: 3
    - name: Tech Team Building
      url: /technology-team-building/
      weight: 2
    - name: Legacy Software Audits
      url: /legacy-custom-software-audits/
      weight: 4

    - name: Trademarks & Patents
      url: /trademarks-and-patents-uk/
      weight: 5
    - name: Research Interests
      url: /research-and-interests/
      weight: 6
    - name: Private DAP
      url: /private-digi-assets-pool/
      weight: 7
    - name: Contact Me
      url: /contact/
      weight: 8


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
